INSERT INTO smulet.professor (id, name, major, email) VALUES (1, '김윤호', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (2, '신경섭', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (3, '강상욱', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (4, '한혁수', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (5, '조민철', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (6, '송병호', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (7, '민경하', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (8, '손성훈', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (9, '민승욱', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (10, '김종욱', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (11, '나재호', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (12, '정대식', 'SW중심대학사업단', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (13, '박종환', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (14, '이석필', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (15, '김진', '빅데이터융합전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (16, '백윤철', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (17, '김영준', '컴퓨터과학전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (18, '문성현', 'SW중심대학사업단', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (19, '장준호', '게임전공', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (20, '강서정', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (21, '강옥희', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (22, '강윤경', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (23, '강혜승', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (24, '곽철안', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (25, '구상균', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (26, '구화목', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (27, '권기환', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (28, '권윤기', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (29, '권정인', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (30, '권지은', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (31, '김경숙', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (32, '김동민', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (33, '김동원', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (34, '김동호', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (35, '김미경', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (36, '김민정', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (37, '김민조', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (38, '김민한', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (39, '김병재', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (40, '김상헌', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (41, '김서기', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (42, '김석규', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (43, '김신욱', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (44, '김예진', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (45, '김용훈', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (46, '김은경', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (47, '김은수', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (48, '김일림', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (49, '김정욱', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (50, '김지안', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (51, '김지현', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (52, '김창배', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (53, '김평강', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (54, '김하연', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (55, '김현주', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (56, '김효정', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (57, '김휘정', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (58, '김희신', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (59, '남진희', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (60, '노동조', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (61, '노주란', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (62, '박건숙', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (63, '박경은', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (64, '박기서', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (65, '박대섭', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (66, '박명숙', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (67, '박선애', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (68, '박수경', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (69, '박옥남', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (70, '박재현', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (71, '박정호', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (72, '박희정', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (73, '반주일', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (74, '방영심', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (75, '배윤한', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (76, '배희분', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (77, '백상현', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (78, '백성수', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (79, '서대희', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (80, '서은숙', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (81, '서인주', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (82, '서주현', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (83, '서지용', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (84, '성윤아', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (85, '성한울', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (86, '손인수', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (87, '송인성', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (88, '심예지', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (89, '심재웅', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (90, '심형근', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (91, '안노마사히데', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (92, '안예진', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (93, '양석준', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (94, '양희순', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (95, '오경은', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (96, '오민석', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (97, '오승준', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (98, '오의경', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (99, '오철', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (100, '왕한호', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (101, '위영민', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (102, '유경원', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (103, '유상건', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (104, '유지연', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (105, '유태종', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (106, '유하영', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (107, '유현주', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (108, '윤지원', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (109, '윤태식', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (110, '이금룡', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (111, '이동진', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (112, '이명호', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (113, '이성호', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (114, '이소연', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (115, '이소현', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (116, '이수철', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (117, '이순명', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (118, '이승배', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (119, '이연숙', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (120, '이유미', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (121, '이윤재', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (122, '이재학', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (123, '이정아', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (124, '이준영', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (125, '이지영', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (126, '이진영', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (127, '이청호', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (128, '이한정', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (129, '이현숙', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (130, '이형국', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (131, '이효', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (132, '장근수', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (133, '장선희', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (134, '장영숙', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (135, '전영옥', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (136, '정다함', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (137, '정수열', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (138, '정순석', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (139, '정유선', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (140, '정의근', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (141, '정의진', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (142, '정재윤', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (143, '정지영', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (144, '정희선', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (145, '정희정', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (146, '조규헌', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (147, '조옥희', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (148, '조일형', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (149, '조태준', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (150, '주경임', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (151, '주애란', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (152, '채유미', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (153, '최영근', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (154, '최원용', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (155, '최윤철', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (156, '최종술', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (157, '최지우', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (158, '최현선', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (159, '최희수', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (160, '프란시스브래넌', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (161, '한규은', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (162, '한만춘', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (163, '한정아', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (164, '함경희', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (165, '홍세령', '전체 학과', null);
INSERT INTO smulet.professor (id, name, major, email) VALUES (166, '황상현', '전체 학과', null);
